export type Recipe = {
  name: string
  time: string
  yield: string
  ingredients: string[]
  steps: string[]
}

export type Category = {
  id: string
  title: string
  image: string
  description: string
  recipes: Recipe[]
}

export type Ficha = {
  tagline: string
  benefits: { icon: 'money' | 'cold' | 'heart'; title: string; text: string }[]
  utensils: string[]
  tip: string
  conservation: string
  sellingPoints: string[]
  price: string
  priceUnit: string
  footer: string
}

export const fichaByCategory: Record<string, Ficha> = {
  bolis: {
    tagline: 'Cremoso, intenso y perfecto para vender. ¡Éxito asegurado en los geladitos brasileños!',
    benefits: [
      { icon: 'money', title: 'Alta rentabilidad', text: 'Bajo costo, gran ganancia.' },
      { icon: 'cold', title: 'Consérvalos congelados', text: 'Listos para vender cuando quieras.' },
      { icon: 'heart', title: 'Sabor que enamora', text: 'Cremoso, intenso e irresistible.' },
    ],
    utensils: ['Olla', 'Batidor', 'Vaso medidor', 'Embudo', 'Bolsas para bolis'],
    tip: 'Usa ingredientes de buena calidad para un sabor más intenso y cremoso.',
    conservation: 'Mantener en congelador. Duran hasta 30 días congelados.',
    sellingPoints: [
      'Ideal para fiestas, eventos y ventas por pedido.',
      'Gran aceptación entre niños y adultos.',
      'Presentación práctica y lista para congelar.',
    ],
    price: '$15 a $25',
    priceUnit: 'por unidad',
    footer: 'Fácil de hacer, delicioso y muy rentable',
  },
  brigadeiros: {
    tagline: 'El dulce brasileño más querido. Cremoso, fácil de hacer y perfecto para vender.',
    benefits: [
      { icon: 'money', title: 'Alta rentabilidad', text: 'Rinden mucho con poco.' },
      { icon: 'cold', title: 'Fáciles de conservar', text: 'Aguantan varios días refrigerados.' },
      { icon: 'heart', title: 'Sabor que enamora', text: 'El dulce más querido de Brasil.' },
    ],
    utensils: ['Olla', 'Cuchara de madera', 'Capacillos', 'Charola'],
    tip: 'Cocina a fuego medio sin dejar de revolver para lograr el punto perfecto.',
    conservation: 'Consérvalos refrigerados hasta 5 días en recipiente cerrado.',
    sellingPoints: [
      'Perfectos para cajas de regalo y eventos.',
      'Se venden muy bien por unidad o por docena.',
      'Fáciles de decorar y personalizar.',
    ],
    price: '$8 a $15',
    priceUnit: 'por unidad',
    footer: 'Fácil de hacer, delicioso y muy rentable',
  },
  vaso: {
    tagline: 'Postre individual, cremoso y muy vistoso. ¡Se vende solo por porción!',
    benefits: [
      { icon: 'money', title: 'Alta rentabilidad', text: 'Postre premium, gran margen.' },
      { icon: 'cold', title: 'Consérvalos refrigerados', text: 'Listos para entregar frescos.' },
      { icon: 'heart', title: 'Sabor que enamora', text: 'Cremoso y muy vistoso.' },
    ],
    utensils: ['Batidor', 'Vasos individuales', 'Cuchara', 'Refractario'],
    tip: 'Arma capas parejas para que se vean bonitos por fuera del vaso.',
    conservation: 'Refrigerar y consumir en un máximo de 3 días.',
    sellingPoints: [
      'Ideales para pedidos y ventas por porción.',
      'Presentación individual muy atractiva.',
      'Fáciles de transportar y entregar.',
    ],
    price: '$30 a $50',
    priceUnit: 'por vaso',
    footer: 'Fácil de hacer, delicioso y muy rentable',
  },
  tartaletas: {
    tagline: 'Crujientes por fuera, cremosas por dentro. Presentación gourmet que impresiona.',
    benefits: [
      { icon: 'money', title: 'Alta rentabilidad', text: 'Elegantes y bien pagadas.' },
      { icon: 'cold', title: 'Consérvalas refrigeradas', text: 'Frescas hasta la entrega.' },
      { icon: 'heart', title: 'Sabor que enamora', text: 'Crujientes y cremosas.' },
    ],
    utensils: ['Horno', 'Molde de tartaletas', 'Batidor', 'Manga pastelera'],
    tip: 'Rellena las tartaletas poco antes de vender para que queden crujientes.',
    conservation: 'Refrigerar hasta 3 días. Decora justo antes de servir.',
    sellingPoints: [
      'Perfectas para mesas de postres y eventos.',
      'Se venden muy bien por unidad.',
      'Presentación gourmet que impresiona.',
    ],
    price: '$20 a $35',
    priceUnit: 'por unidad',
    footer: 'Fácil de hacer, delicioso y muy rentable',
  },
  postres: {
    tagline: 'Postres fríos cremosos e irresistibles. Perfectos para vender por porción.',
    benefits: [
      { icon: 'money', title: 'Alta rentabilidad', text: 'Bajo costo, gran ganancia.' },
      { icon: 'cold', title: 'Consérvalos refrigerados', text: 'Listos para entregar frescos.' },
      { icon: 'heart', title: 'Sabor que enamora', text: 'Cremosos e irresistibles.' },
    ],
    utensils: ['Batidor', 'Copas o vasos', 'Cuchara', 'Refractario'],
    tip: 'Decora la superficie con fruta o chocolate para que luzca más atractivo.',
    conservation: 'Refrigerar y consumir en un máximo de 3 días.',
    sellingPoints: [
      'Ideales para ventas por porción.',
      'Muy populares en fechas especiales.',
      'Se preparan con anticipación sin problema.',
    ],
    price: '$25 a $45',
    priceUnit: 'por porción',
    footer: 'Fácil de hacer, delicioso y muy rentable',
  },
  combos: {
    tagline: 'Combina tus dulces más vendidos y aumenta el valor de cada pedido.',
    benefits: [
      { icon: 'money', title: 'Mayor ticket', text: 'Aumenta el valor de cada venta.' },
      { icon: 'cold', title: 'Armado flexible', text: 'Combina tus dulces más vendidos.' },
      { icon: 'heart', title: 'Regalo perfecto', text: 'Ideales para sorprender.' },
    ],
    utensils: ['Cajas', 'Etiquetas', 'Moños', 'Bolsas'],
    tip: 'Ofrece un pequeño descuento en el combo para que sea más atractivo que comprar suelto.',
    conservation: 'Según los dulces incluidos en el combo.',
    sellingPoints: [
      'Aumentan el valor promedio de cada pedido.',
      'Perfectos para fechas especiales y regalos.',
      'Fáciles de armar con lo que ya preparas.',
    ],
    price: '$80 a $200',
    priceUnit: 'por combo',
    footer: 'Fácil de armar, vistoso y muy rentable',
  },
}

// Helpers para mantener las 150 recetas consistentes y compactas
const boli = (
  name: string,
  ingredients: string[],
  extraStep?: string,
): Recipe => ({
  name,
  time: '15 min + congelado',
  yield: '15 bolis',
  ingredients,
  steps: [
    'Licúa o mezcla todos los ingredientes hasta obtener una mezcla homogénea.',
    extraStep ?? 'Prueba el dulzor y ajusta a tu gusto.',
    'Rellena las bolsitas para boli dejando un poco de espacio y amarra bien.',
    'Congela por al menos 6 horas antes de vender.',
  ],
})

const brigadeiro = (
  name: string,
  ingredients: string[],
  deco: string,
): Recipe => ({
  name,
  time: '20 min',
  yield: '20 unidades',
  ingredients,
  steps: [
    'Cocina la mezcla a fuego medio revolviendo sin parar.',
    'Cuando se despegue del fondo de la olla, retira y deja enfriar.',
    'Unta mantequilla en tus manos y forma bolitas.',
    `Decora con ${deco} y coloca en capacillos.`,
  ],
})

const vaso = (
  name: string,
  ingredients: string[],
  montaje: string,
): Recipe => ({
  name,
  time: '40 min',
  yield: '6 vasos',
  ingredients,
  steps: [
    'Prepara la crema base cocinando o batiendo los ingredientes cremosos.',
    montaje,
    'Alterna capas hasta llenar el vaso y termina con crema y decoración.',
    'Refrigera por al menos 2 horas antes de vender.',
  ],
})

const tartaleta = (
  name: string,
  ingredients: string[],
  relleno: string,
): Recipe => ({
  name,
  time: '45 min',
  yield: '10 unidades',
  ingredients,
  steps: [
    'Hornea las bases de tartaleta hasta dorar y deja enfriar.',
    relleno,
    'Rellena las tartaletas de forma pareja.',
    'Refrigera y decora justo antes de servir.',
  ],
})

const postre = (
  name: string,
  ingredients: string[],
  prep: string,
): Recipe => ({
  name,
  time: '25 min + refrigerado',
  yield: '8 porciones',
  ingredients,
  steps: [
    prep,
    'Sirve en copas o vasitos individuales.',
    'Decora la superficie de forma atractiva.',
    'Refrigera por al menos 3 horas antes de vender.',
  ],
})

const combo = (
  name: string,
  yieldText: string,
  ingredients: string[],
): Recipe => ({
  name,
  time: 'Armado',
  yield: yieldText,
  ingredients,
  steps: [
    'Selecciona una variedad de tus dulces más vendidos.',
    'Acomoda en una caja o empaque bonito con separadores.',
    'Agrega una etiqueta con tu marca y una tarjeta de agradecimiento.',
    'Ofrece el combo a un precio especial para aumentar el ticket.',
  ],
})

const CREMA_BASE = ['1 lata de leche condensada', '1 caja de crema de leche (200 g)', '2 tazas de leche']

export function recipeSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

export function posterPath(name: string): string {
  return `/dulces/posters/${recipeSlug(name)}.png`
}

export function coverPath(name: string): string {
  return `/dulces/covers/${recipeSlug(name)}.png`
}

// Recetas que ya tienen su portada individual (foto limpia del dulce) generada
export const coversReady = new Set<string>([
  'boli-de-chocolate-cremoso',
  'boli-de-fresa-con-leche',
  'boli-de-coco',
  'boli-de-maracuya',
  'boli-de-chocolate-con-fresa',
  'boli-de-ninho-con-nutella',
  'boli-de-oreo',
  'boli-de-limon',
  'boli-de-mango',
  'boli-pina-colada',
  'boli-de-uva',
  'boli-de-vainilla',
  'boli-de-cafe',
  'boli-de-dulce-de-leche',
  'boli-de-platano-con-canela',
  'boli-de-chocolate-blanco',
  'boli-de-menta-con-chocolate',
  'boli-de-frutos-rojos',
  'boli-de-durazno',
  'boli-de-cajeta',
  'boli-de-nuez',
  'boli-de-galleta-maria',
  'boli-de-yogurt-con-fresa',
  'boli-de-sandia',
  'boli-de-tamarindo',
  'boli-de-guayaba',
  'boli-de-chicle-azul',
  'boli-de-amarena',
  'boli-de-pistache',
  'boli-de-chocolate-con-menta',
  'brigadeiro-tradicional',
  'brigadeiro-de-coco-beijinho',
  'brigadeiro-de-pistache',
  'brigadeiro-de-ninho',
  'brigadeiro-de-nutella',
  'brigadeiro-de-churros',
  'brigadeiro-de-maracuya',
  'brigadeiro-de-limon',
  'brigadeiro-de-cafe',
  'brigadeiro-de-chocolate-blanco',
  'brigadeiro-de-fresa',
  'brigadeiro-de-dulce-de-leche',
  'brigadeiro-de-nuez',
  'brigadeiro-de-oreo',
  'brigadeiro-amargo-70',
  'brigadeiro-de-coco-quemado',
  'brigadeiro-de-cajeta',
  'brigadeiro-de-mani',
  'brigadeiro-de-chocolate-con-naranja',
  'brigadeiro-de-frambuesa',
  'brigadeiro-bicho-de-pe-fresa',
  'brigadeiro-ninho-con-nutella',
  'brigadeiro-prestigio',
  'brigadeiro-cookies-and-cream',
  'brigadeiro-de-menta',
  'brigadeiro-de-capuchino',
  'brigadeiro-de-zanahoria',
  'brigadeiro-de-limon-con-merengue',
  'brigadeiro-de-chocolate-con-chile',
  'brigadeiro-de-vainilla',
  'pastel-en-vaso-de-chocolate',
  'pastel-en-vaso-de-fresa',
  'pastel-en-vaso-de-zanahoria-con-chocolate',
  'tres-leches-brasileno-en-vaso',
  'pastel-en-vaso-ninho-con-nutella',
  'pastel-en-vaso-de-maracuya',
  'pastel-en-vaso-de-limon',
  'pastel-en-vaso-prestigio',
  'pastel-en-vaso-de-dulce-de-leche',
  'pastel-en-vaso-de-oreo',
  'pastel-en-vaso-de-platano',
  'pastel-en-vaso-de-coco',
  'pastel-en-vaso-de-cafe',
  'pastel-choco-blanco-con-frambuesa',
  'pastel-en-vaso-de-pina',
  'pastel-en-vaso-de-durazno',
  'pastel-en-vaso-bombon',
  'pastel-choco-con-naranja',
  'pastel-en-vaso-red-velvet',
  'pastel-nuez-con-cajeta',
  'pastel-de-frutos-rojos',
  'pastel-menta-con-chocolate',
  'pastel-vainilla-con-cajeta',
  'pastel-en-vaso-de-pistache',
  'pastel-en-vaso-de-cookies',
  'tartaleta-de-limon',
  'tartaleta-de-chocolate',
  'tartaleta-de-fresa',
  'tartaleta-de-maracuya',
  'tartaleta-de-dulce-de-leche',
  'tartaleta-de-coco',
  'tartaleta-de-frutos-rojos',
  'tartaleta-de-manzana',
  'tartaleta-de-nuez',
  'tartaleta-de-cafe',
  'tartaleta-de-ninho',
  'tartaleta-de-nutella',
  'tartaleta-de-pina',
  'tartaleta-de-durazno',
  'tartaleta-de-queso-con-zarzamora',
  'tartaleta-de-pistache',
  'tartaleta-de-naranja',
  'tartaleta-de-cajeta',
  'tartaleta-de-mango',
  'tartaleta-de-chocolate-blanco',
  'mousse-de-maracuya',
  'pave-brasileno-de-galleta',
  'crema-de-coco',
  'chocolate-frio',
  'postre-de-fresa',
  'mousse-de-chocolate',
  'mousse-de-limon',
  'copa-de-ninho',
  'tiramisu-brasileno',
  'gelatina-de-mosaico',
  'manjar-blanco',
  'flan-de-coco',
  'mousse-de-fresa',
  'copa-prestigio',
  'cheesecake-frio-de-frutos-rojos',
  'copa-de-dulce-de-leche',
  'mousse-de-cafe',
  'copa-de-oreo',
  'pudin-de-chocolate',
  'mousse-maracuya-con-chocolate',
  'copa-de-durazno',
  'crema-de-vainilla-con-cajeta',
  'mousse-de-mango',
  'copa-de-nuez',
  'gelatina-cremosa-de-fresa',
  'caja-degustacion-12-dulces',
  'combo-familiar',
  'kit-de-brigadeiros-x25',
  'combo-de-bolis-x10',
  'caja-san-valentin',
  'kit-cumpleanos',
  'combo-fin-de-semana',
  'caja-premium',
  'kit-para-fiestas',
  'combo-cafeteria',
  'caja-de-regalo',
  'combo-dia-de-las-madres',
  'kit-empresarial',
  'combo-merienda',
  'caja-surtida-mini',
  'combo-navideno',
  'kit-antojo-nocturno',
  'combo-pareja',
  'caja-corporativa',
  'kit-emprendedora',
])

// Recetas que ya tienen su póster (arte) generado
export const postersReady = new Set<string>([
  'boli-de-chocolate-cremoso',
  'boli-de-fresa-con-leche',
  'boli-de-coco',
  'boli-de-maracuya',
  'boli-de-chocolate-con-fresa',
  'boli-de-ninho-con-nutella',
  'boli-de-oreo',
  'boli-de-limon',
  'boli-de-mango',
  'boli-pina-colada',
  'boli-de-uva',
  'boli-de-vainilla',
  'boli-de-cafe',
  'boli-de-dulce-de-leche',
  'boli-de-platano-con-canela',
  'boli-de-chocolate-blanco',
  'boli-de-menta-con-chocolate',
  'boli-de-frutos-rojos',
  'boli-de-durazno',
  'boli-de-cajeta',
  'boli-de-nuez',
  'boli-de-galleta-maria',
  'boli-de-yogurt-con-fresa',
  'boli-de-sandia',
  'boli-de-tamarindo',
  'boli-de-guayaba',
  'boli-de-chicle-azul',
  'boli-de-amarena',
  'boli-de-pistache',
  'boli-de-chocolate-con-menta',
  'brigadeiro-tradicional',
  'brigadeiro-de-coco-beijinho',
  'brigadeiro-de-pistache',
  'brigadeiro-de-ninho',
  'brigadeiro-de-nutella',
  'brigadeiro-de-churros',
  'brigadeiro-de-maracuya',
  'brigadeiro-de-limon',
  'brigadeiro-de-cafe',
  'brigadeiro-de-chocolate-blanco',
  'brigadeiro-de-fresa',
  'brigadeiro-de-dulce-de-leche',
  'brigadeiro-de-nuez',
  'brigadeiro-de-oreo',
  'brigadeiro-amargo-70',
  'brigadeiro-de-coco-quemado',
  'brigadeiro-de-cajeta',
  'brigadeiro-de-mani',
  'brigadeiro-de-chocolate-con-naranja',
  'brigadeiro-de-frambuesa',
  'brigadeiro-bicho-de-pe-fresa',
  'brigadeiro-ninho-con-nutella',
  'brigadeiro-prestigio',
  'brigadeiro-cookies-and-cream',
  'brigadeiro-de-menta',
  'brigadeiro-de-capuchino',
  'brigadeiro-de-zanahoria',
  'brigadeiro-de-limon-con-merengue',
  'brigadeiro-de-chocolate-con-chile',
  'brigadeiro-de-vainilla',
  'pastel-en-vaso-de-chocolate',
  'pastel-en-vaso-de-fresa',
  'pastel-en-vaso-de-zanahoria-con-chocolate',
  'tres-leches-brasileno-en-vaso',
  'pastel-en-vaso-ninho-con-nutella',
  'pastel-en-vaso-de-maracuya',
  'pastel-en-vaso-de-limon',
  'pastel-en-vaso-prestigio',
  'pastel-en-vaso-de-dulce-de-leche',
  'pastel-en-vaso-de-oreo',
  'pastel-en-vaso-de-platano',
  'pastel-en-vaso-de-coco',
  'pastel-en-vaso-de-cafe',
  'pastel-choco-blanco-con-frambuesa',
  'pastel-en-vaso-de-pina',
  'pastel-en-vaso-de-durazno',
  'pastel-en-vaso-bombon',
  'pastel-choco-con-naranja',
  'pastel-en-vaso-red-velvet',
  'pastel-nuez-con-cajeta',
  'pastel-de-frutos-rojos',
  'pastel-menta-con-chocolate',
  'pastel-vainilla-con-cajeta',
  'pastel-en-vaso-de-pistache',
  'pastel-en-vaso-de-cookies',
  'tartaleta-de-limon',
  'tartaleta-de-chocolate',
  'tartaleta-de-fresa',
  'tartaleta-de-maracuya',
  'tartaleta-de-dulce-de-leche',
  'tartaleta-de-coco',
  'tartaleta-de-frutos-rojos',
  'tartaleta-de-manzana',
  'tartaleta-de-nuez',
  'tartaleta-de-cafe',
  'tartaleta-de-ninho',
  'tartaleta-de-nutella',
  'tartaleta-de-pina',
  'tartaleta-de-durazno',
  'tartaleta-de-queso-con-zarzamora',
  'tartaleta-de-pistache',
  'tartaleta-de-naranja',
  'tartaleta-de-cajeta',
  'tartaleta-de-mango',
  'tartaleta-de-chocolate-blanco',
  'mousse-de-maracuya',
  'pave-brasileno-de-galleta',
  'crema-de-coco',
  'chocolate-frio',
  'postre-de-fresa',
  'mousse-de-chocolate',
  'mousse-de-limon',
  'copa-de-ninho',
  'tiramisu-brasileno',
  'gelatina-de-mosaico',
  'manjar-blanco',
  'flan-de-coco',
  'mousse-de-fresa',
  'copa-prestigio',
  'cheesecake-frio-de-frutos-rojos',
  'copa-de-dulce-de-leche',
  'mousse-de-cafe',
  'copa-de-oreo',
  'pudin-de-chocolate',
  'mousse-maracuya-con-chocolate',
  'copa-de-durazno',
  'crema-de-vainilla-con-cajeta',
  'mousse-de-mango',
  'copa-de-nuez',
  'gelatina-cremosa-de-fresa',
  'caja-degustacion-12-dulces',
  'combo-familiar',
  'kit-de-brigadeiros-x25',
  'combo-de-bolis-x10',
  'caja-san-valentin',
  'kit-cumpleanos',
  'combo-fin-de-semana',
  'caja-premium',
  'kit-para-fiestas',
  'combo-cafeteria',
  'caja-de-regalo',
  'combo-dia-de-las-madres',
  'kit-empresarial',
  'combo-merienda',
  'caja-surtida-mini',
  'combo-navideno',
  'kit-antojo-nocturno',
  'combo-pareja',
  'caja-corporativa',
  'kit-emprendedora',
])

export const categories: Category[] = [
  {
    id: 'bolis',
    title: 'Bolis Brasileños Gourmet',
    image: '/dulces/bolis.png',
    description: 'Sabores cremosos y frutales inspirados en los geladinhos brasileños. 30 recetas.',
    recipes: [
      boli('Boli de Chocolate Cremoso', [...CREMA_BASE, '4 cucharadas de cacao', '100 g de chocolate semiamargo']),
      boli('Boli de Fresa con Leche', [...CREMA_BASE, '2 tazas de fresas frescas']),
      boli('Boli de Coco', ['1 lata de leche condensada', '1 lata de leche de coco', '2 tazas de leche', '1 taza de coco rallado']),
      boli('Boli de Maracuyá', [...CREMA_BASE, '1 taza de pulpa de maracuyá']),
      boli('Boli de Chocolate con Fresa', [...CREMA_BASE, '3 cucharadas de cacao', '1 taza de fresas picadas']),
      boli('Boli de Ninho con Nutella', [...CREMA_BASE, '4 cucharadas de leche en polvo', '4 cucharadas de Nutella']),
      boli('Boli de Oreo', [...CREMA_BASE, '8 galletas Oreo trituradas']),
      boli('Boli de Limón', [...CREMA_BASE, 'Jugo y ralladura de 2 limones']),
      boli('Boli de Mango', [...CREMA_BASE, '2 mangos maduros en pulpa']),
      boli('Boli Piña Colada', ['1 lata de leche condensada', '1 lata de leche de coco', '1 taza de piña picada', '2 tazas de leche']),
      boli('Boli de Uva', [...CREMA_BASE, '1 taza de jugo concentrado de uva']),
      boli('Boli de Vainilla', [...CREMA_BASE, '1 cucharada de esencia de vainilla']),
      boli('Boli de Café', [...CREMA_BASE, '2 cucharadas de café soluble']),
      boli('Boli de Dulce de Leche', [...CREMA_BASE, '1 taza de dulce de leche']),
      boli('Boli de Plátano con Canela', [...CREMA_BASE, '2 plátanos maduros', '1 cucharadita de canela']),
      boli('Boli de Chocolate Blanco', [...CREMA_BASE, '150 g de chocolate blanco derretido']),
      boli('Boli de Menta con Chocolate', [...CREMA_BASE, '1 cucharadita de esencia de menta', 'chispas de chocolate']),
      boli('Boli de Frutos Rojos', [...CREMA_BASE, '1 taza de frutos rojos mixtos']),
      boli('Boli de Durazno', [...CREMA_BASE, '1 taza de duraznos en almíbar']),
      boli('Boli de Cajeta', [...CREMA_BASE, '1 taza de cajeta']),
      boli('Boli de Nuez', [...CREMA_BASE, '1 taza de nuez molida']),
      boli('Boli de Galleta María', [...CREMA_BASE, '10 galletas María trituradas']),
      boli('Boli de Yogurt con Fresa', ['1 lata de leche condensada', '2 tazas de yogurt natural', '1 taza de fresas']),
      boli('Boli de Sandía', ['1 lata de leche condensada', '3 tazas de sandía sin semillas', '1 taza de leche']),
      boli('Boli de Tamarindo', [...CREMA_BASE, '1 taza de pulpa de tamarindo']),
      boli('Boli de Guayaba', [...CREMA_BASE, '1 taza de pulpa de guayaba']),
      boli('Boli de Chicle (Azul)', [...CREMA_BASE, '2 cucharadas de esencia de chicle', 'colorante azul']),
      boli('Boli de Amarena', [...CREMA_BASE, '1 taza de cerezas amarena']),
      boli('Boli de Pistache', [...CREMA_BASE, '3 cucharadas de pasta de pistache']),
      boli('Boli de Chocolate con Menta', [...CREMA_BASE, '3 cucharadas de cacao', '1 cucharadita de esencia de menta']),
    ],
  },
  {
    id: 'brigadeiros',
    title: 'Brigadeiros Brasileños',
    image: '/dulces/brigadeiros.png',
    description: 'El dulce más famoso de Brasil, en versiones tradicionales y gourmet. 30 recetas.',
    recipes: [
      brigadeiro('Brigadeiro Tradicional', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de cacao'], 'chispas de chocolate'),
      brigadeiro('Brigadeiro de Coco (Beijinho)', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de coco rallado'], 'coco rallado'),
      brigadeiro('Brigadeiro de Pistache', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de pasta de pistache'], 'pistaches picados'),
      brigadeiro('Brigadeiro de Ninho', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de leche en polvo'], 'leche en polvo'),
      brigadeiro('Brigadeiro de Nutella', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de Nutella'], 'avellanas picadas'),
      brigadeiro('Brigadeiro de Churros', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1 cucharadita de canela', 'dulce de leche'], 'azúcar con canela'),
      brigadeiro('Brigadeiro de Maracuyá', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de pulpa de maracuy��'], 'ralladura de chocolate blanco'),
      brigadeiro('Brigadeiro de Limón', ['1 lata de leche condensada', '1 cucharada de mantequilla', 'ralladura de 1 limón'], 'ralladura de limón'),
      brigadeiro('Brigadeiro de Café', ['1 lata de leche condensada', '1 cucharada de mantequilla', '2 cucharadas de café soluble'], 'granos de café de chocolate'),
      brigadeiro('Brigadeiro de Chocolate Blanco', ['1 lata de leche condensada', '1 cucharada de mantequilla', '100 g de chocolate blanco'], 'chispas blancas'),
      brigadeiro('Brigadeiro de Fresa', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de gelatina de fresa'], 'granillo rosa'),
      brigadeiro('Brigadeiro de Dulce de Leche', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1/2 taza de dulce de leche'], 'chispas de chocolate'),
      brigadeiro('Brigadeiro de Nuez', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1/2 taza de nuez molida'], 'nuez picada'),
      brigadeiro('Brigadeiro de Oreo', ['1 lata de leche condensada', '1 cucharada de mantequilla', '6 galletas Oreo trituradas'], 'trozos de Oreo'),
      brigadeiro('Brigadeiro Amargo 70%', ['1 lata de leche condensada', '1 cucharada de mantequilla', '100 g de chocolate 70%'], 'cacao en polvo'),
      brigadeiro('Brigadeiro de Coco Quemado', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de coco tostado'], 'coco tostado'),
      brigadeiro('Brigadeiro de Cajeta', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1/2 taza de cajeta'], 'chispas de caramelo'),
      brigadeiro('Brigadeiro de Maní', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de crema de maní'], 'maní picado'),
      brigadeiro('Brigadeiro de Chocolate con Naranja', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de cacao', 'ralladura de naranja'], 'ralladura de naranja'),
      brigadeiro('Brigadeiro de Frambuesa', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de mermelada de frambuesa'], 'granillo rojo'),
      brigadeiro('Brigadeiro Bicho de Pé (Fresa)', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de gelatina de fresa'], 'azúcar rosa'),
      brigadeiro('Brigadeiro Ninho con Nutella', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de leche en polvo', 'Nutella para rellenar'], 'leche en polvo'),
      brigadeiro('Brigadeiro Prestígio', ['1 lata de leche condensada', '1 cucharada de mantequilla', '3 cucharadas de coco', '3 cucharadas de cacao'], 'coco rallado'),
      brigadeiro('Brigadeiro Cookies and Cream', ['1 lata de leche condensada', '1 cucharada de mantequilla', '100 g de chocolate blanco', '5 galletas Oreo'], 'trozos de galleta'),
      brigadeiro('Brigadeiro de Menta', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de cacao', '1 cucharadita de menta'], 'chispas verdes'),
      brigadeiro('Brigadeiro de Capuchino', ['1 lata de leche condensada', '1 cucharada de mantequilla', '2 cucharadas de café', '2 cucharadas de cacao'], 'cacao en polvo'),
      brigadeiro('Brigadeiro de Zanahoria', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1/2 taza de zanahoria cocida', '2 cucharadas de cacao'], 'chispas de chocolate'),
      brigadeiro('Brigadeiro de Limón con Merengue', ['1 lata de leche condensada', '1 cucharada de mantequilla', 'jugo de 1 limón'], 'merengue seco'),
      brigadeiro('Brigadeiro de Chocolate con Chile', ['1 lata de leche condensada', '1 cucharada de mantequilla', '4 cucharadas de cacao', 'pizca de chile en polvo'], 'chile con azúcar'),
      brigadeiro('Brigadeiro de Vainilla', ['1 lata de leche condensada', '1 cucharada de mantequilla', '1 cucharadita de vainilla'], 'granillo de colores'),
    ],
  },
  {
    id: 'vaso',
    title: 'Pasteles en Vaso',
    image: '/dulces/vaso.png',
    description: 'Versiones individuales inspiradas en los bolos de pote brasileños. 25 recetas.',
    recipes: [
      vaso('Pastel en Vaso de Chocolate', ['Bizcocho de chocolate', ...CREMA_BASE, 'chispas de chocolate'], 'Coloca una capa de bizcocho de chocolate en el fondo.'),
      vaso('Pastel en Vaso de Fresa', ['Bizcocho de vainilla', ...CREMA_BASE, 'fresas picadas'], 'Coloca bizcocho y fresas frescas en el fondo.'),
      vaso('Pastel en Vaso de Zanahoria con Chocolate', ['Bizcocho de zanahoria', ...CREMA_BASE, '4 cucharadas de cacao'], 'Alterna bizcocho de zanahoria con crema de chocolate.'),
      vaso('Tres Leches Brasileño en Vaso', ['Bizcocho esponjoso', '3 tipos de leche', 'crema batida'], 'Remoja el bizcocho con la mezcla de tres leches.'),
      vaso('Pastel en Vaso Ninho con Nutella', ['Bizcocho de vainilla', ...CREMA_BASE, 'leche en polvo', 'Nutella'], 'Alterna crema de ninho con Nutella y bizcocho.'),
      vaso('Pastel en Vaso de Maracuyá', ['Bizcocho de vainilla', ...CREMA_BASE, 'pulpa de maracuyá'], 'Coloca bizcocho y baña con pulpa de maracuyá.'),
      vaso('Pastel en Vaso de Limón', ['Bizcocho de vainilla', ...CREMA_BASE, 'jugo de limón'], 'Alterna crema de limón con bizcocho.'),
      vaso('Pastel en Vaso Prestígio', ['Bizcocho de chocolate', ...CREMA_BASE, 'coco rallado'], 'Alterna crema de coco con bizcocho de chocolate.'),
      vaso('Pastel en Vaso de Dulce de Leche', ['Bizcocho de vainilla', ...CREMA_BASE, 'dulce de leche'], 'Alterna dulce de leche con crema y bizcocho.'),
      vaso('Pastel en Vaso de Oreo', ['Galletas Oreo', ...CREMA_BASE, '100 g de chocolate blanco'], 'Tritura Oreo y alterna con crema.'),
      vaso('Pastel en Vaso de Plátano', ['Bizcocho de vainilla', ...CREMA_BASE, 'plátano', 'canela'], 'Alterna plátano en rodajas con crema.'),
      vaso('Pastel en Vaso de Coco', ['Bizcocho de vainilla', '1 lata de leche de coco', ...CREMA_BASE, 'coco rallado'], 'Baña el bizcocho con leche de coco.'),
      vaso('Pastel en Vaso de Café', ['Bizcocho de chocolate', ...CREMA_BASE, 'café soluble'], 'Remoja el bizcocho en café y alterna con crema.'),
      vaso('Pastel Choco Blanco con Frambuesa', ['Bizcocho de vainilla', ...CREMA_BASE, 'chocolate blanco', 'frambuesas'], 'Alterna crema de chocolate blanco con frambuesa.'),
      vaso('Pastel en Vaso de Piña', ['Bizcocho de vainilla', ...CREMA_BASE, 'piña picada'], 'Alterna piña con crema y bizcocho.'),
      vaso('Pastel en Vaso de Durazno', ['Bizcocho de vainilla', ...CREMA_BASE, 'duraznos en almíbar'], 'Alterna duraznos picados con crema.'),
      vaso('Pastel en Vaso Bombón', ['Bizcocho de chocolate', ...CREMA_BASE, 'chocolate', 'fresas'], 'Alterna crema, fresa y ganache de chocolate.'),
      vaso('Pastel Choco con Naranja', ['Bizcocho de chocolate', ...CREMA_BASE, 'ralladura de naranja'], 'Alterna crema con ralladura de naranja.'),
      vaso('Pastel en Vaso Red Velvet', ['Bizcocho red velvet', ...CREMA_BASE, 'queso crema'], 'Alterna bizcocho rojo con crema de queso.'),
      vaso('Pastel Nuez con Cajeta', ['Bizcocho de vainilla', ...CREMA_BASE, 'cajeta', 'nuez'], 'Alterna cajeta y nuez con crema.'),
      vaso('Pastel de Frutos Rojos', ['Bizcocho de vainilla', ...CREMA_BASE, 'frutos rojos'], 'Alterna frutos rojos con crema.'),
      vaso('Pastel Menta con Chocolate', ['Bizcocho de chocolate', ...CREMA_BASE, 'esencia de menta', 'chispas'], 'Alterna crema de menta con bizcocho.'),
      vaso('Pastel Vainilla con Cajeta', ['Bizcocho de vainilla', ...CREMA_BASE, 'cajeta'], 'Alterna cajeta con crema de vainilla.'),
      vaso('Pastel en Vaso de Pistache', ['Bizcocho de vainilla', ...CREMA_BASE, 'pasta de pistache'], 'Alterna crema de pistache con bizcocho.'),
      vaso('Pastel en Vaso de Cookies', ['Galletas de chocolate', ...CREMA_BASE, 'chispas'], 'Alterna galleta triturada con crema.'),
    ],
  },
  {
    id: 'tartaletas',
    title: 'Tartaletas Gourmet',
    image: '/dulces/tartaletas.png',
    description: 'Tortitas dulces individuales, bonitas y fáciles de vender por unidad. 20 recetas.',
    recipes: [
      tartaleta('Tartaleta de Limón', ['Masa para tartaleta', '1 lata de leche condensada', 'jugo de 3 limones', '2 yemas', 'merengue'], 'Mezcla leche condensada, jugo de limón y yemas.'),
      tartaleta('Tartaleta de Chocolate', ['Masa para tartaleta', '200 g de chocolate', '1 caja de crema de leche', 'frutos rojos'], 'Prepara una ganache con chocolate y crema de leche.'),
      tartaleta('Tartaleta de Fresa', ['Masa para tartaleta', 'crema pastelera', 'fresas frescas', 'brillo de mermelada'], 'Rellena con crema pastelera y cubre con fresas.'),
      tartaleta('Tartaleta de Maracuyá', ['Masa para tartaleta', '1 lata de leche condensada', 'pulpa de maracuyá', '2 yemas'], 'Mezcla leche condensada con pulpa de maracuyá.'),
      tartaleta('Tartaleta de Dulce de Leche', ['Masa para tartaleta', 'dulce de leche', 'crema batida', 'nuez'], 'Rellena con dulce de leche espeso.'),
      tartaleta('Tartaleta de Coco', ['Masa para tartaleta', '1 lata de leche condensada', 'coco rallado', '1 huevo'], 'Mezcla leche condensada con coco y huevo.'),
      tartaleta('Tartaleta de Frutos Rojos', ['Masa para tartaleta', 'crema pastelera', 'frutos rojos mixtos'], 'Rellena con crema y cubre con frutos rojos.'),
      tartaleta('Tartaleta de Manzana', ['Masa para tartaleta', 'manzanas', 'azúcar', 'canela'], 'Cocina las manzanas con azúcar y canela.'),
      tartaleta('Tartaleta de Nuez', ['Masa para tartaleta', 'nuez', 'cajeta', 'crema de leche'], 'Mezcla nuez con cajeta para el relleno.'),
      tartaleta('Tartaleta de Café', ['Masa para tartaleta', 'crema de café', 'chocolate'], 'Prepara una crema de café con chocolate.'),
      tartaleta('Tartaleta de Ninho', ['Masa para tartaleta', 'leche en polvo', '1 lata de leche condensada', 'crema de leche'], 'Prepara una crema de ninho firme.'),
      tartaleta('Tartaleta de Nutella', ['Masa para tartaleta', 'Nutella', 'crema batida', 'avellanas'], 'Rellena con Nutella y crema batida.'),
      tartaleta('Tartaleta de Piña', ['Masa para tartaleta', 'piña', 'crema pastelera'], 'Rellena con crema y cubre con piña caramelizada.'),
      tartaleta('Tartaleta de Durazno', ['Masa para tartaleta', 'crema pastelera', 'duraznos'], 'Rellena con crema y cubre con duraznos.'),
      tartaleta('Tartaleta de Queso con Zarzamora', ['Masa para tartaleta', 'queso crema', 'azúcar', 'zarzamoras'], 'Bate queso crema con azúcar para el relleno.'),
      tartaleta('Tartaleta de Pistache', ['Masa para tartaleta', 'pasta de pistache', 'crema de leche'], 'Prepara una crema de pistache.'),
      tartaleta('Tartaleta de Naranja', ['Masa para tartaleta', '1 lata de leche condensada', 'jugo de naranja', '2 yemas'], 'Mezcla leche condensada con jugo de naranja.'),
      tartaleta('Tartaleta de Cajeta', ['Masa para tartaleta', 'cajeta', 'crema batida'], 'Rellena con cajeta espesa.'),
      tartaleta('Tartaleta de Mango', ['Masa para tartaleta', 'crema pastelera', 'mango'], 'Rellena con crema y cubre con mango.'),
      tartaleta('Tartaleta de Chocolate Blanco', ['Masa para tartaleta', '200 g de chocolate blanco', 'crema de leche', 'frambuesas'], 'Prepara una ganache de chocolate blanco.'),
    ],
  },
  {
    id: 'postres',
    title: 'Postres Fríos para Vender',
    image: '/dulces/postres.png',
    description: 'Postres cremosos montados en vaso o copa individual. 25 recetas.',
    recipes: [
      postre('Mousse de Maracuyá', ['1 lata de leche condensada', '1 caja de crema de leche', 'pulpa de maracuyá'], 'Licúa todos los ingredientes hasta que espese.'),
      postre('Pavé Brasileño de Galleta', ['galletas María', '1 lata de leche condensada', '2 tazas de leche', '2 yemas', 'crema batida'], 'Cocina leche, leche condensada y yemas hasta formar crema.'),
      postre('Crema de Coco', ['1 lata de leche de coco', '1 lata de leche condensada', 'crema de leche', 'coco rallado'], 'Mezcla las leches con la crema hasta integrar.'),
      postre('Chocolate Frío', ['1 lata de leche condensada', 'cacao', 'crema de leche', 'chocolate'], 'Cocina una crema espesa de chocolate y deja enfriar.'),
      postre('Postre de Fresa', ['fresas', '1 lata de leche condensada', 'crema de leche', 'galletas'], 'Alterna crema de fresa con galletas.'),
      postre('Mousse de Chocolate', ['200 g de chocolate', 'crema de leche', '2 claras batidas'], 'Derrite el chocolate y mezcla con crema y claras.'),
      postre('Mousse de Limón', ['1 lata de leche condensada', 'crema de leche', 'jugo de limón'], 'Licúa hasta que espese con el jugo de limón.'),
      postre('Copa de Ninho', ['leche en polvo', '1 lata de leche condensada', 'crema de leche'], 'Bate hasta obtener una crema firme de ninho.'),
      postre('Tiramisú Brasileño', ['galletas', 'café', 'queso mascarpone', 'crema batida', 'cacao'], 'Remoja galletas en café y alterna con crema de mascarpone.'),
      postre('Gelatina de Mosaico', ['gelatinas de colores', 'leche condensada', 'gelatina sin sabor'], 'Corta gelatinas de colores y cubre con crema de leche.'),
      postre('Manjar Blanco', ['1 lata de leche condensada', 'maicena', 'leche', 'vainilla'], 'Cocina hasta espesar y deja enfriar.'),
      postre('Flan de Coco', ['1 lata de leche condensada', 'leche de coco', '3 huevos', 'caramelo'], 'Licúa y hornea a baño maría (o refrigera con grenetina).'),
      postre('Mousse de Fresa', ['fresas', '1 lata de leche condensada', 'crema de leche'], 'Licúa hasta que espese.'),
      postre('Copa Prestígio', ['crema de coco', 'crema de chocolate', 'coco rallado'], 'Alterna crema de coco con crema de chocolate.'),
      postre('Cheesecake Frío de Frutos Rojos', ['queso crema', 'leche condensada', 'galletas', 'frutos rojos'], 'Bate queso crema con leche condensada sobre base de galleta.'),
      postre('Copa de Dulce de Leche', ['dulce de leche', 'crema batida', 'galletas'], 'Alterna dulce de leche con crema y galleta.'),
      postre('Mousse de Café', ['1 lata de leche condensada', 'crema de leche', 'café soluble'], 'Licúa la crema con el café hasta espesar.'),
      postre('Copa de Oreo', ['galletas Oreo', 'queso crema', 'leche condensada', 'crema batida'], 'Alterna Oreo triturada con crema.'),
      postre('Pudín de Chocolate', ['leche', 'cacao', 'maicena', 'azúcar'], 'Cocina hasta espesar y deja cuajar.'),
      postre('Mousse Maracuyá con Chocolate', ['pulpa de maracuyá', 'leche condensada', 'crema de leche', 'chocolate'], 'Prepara mousse de maracuyá sobre ganache de chocolate.'),
      postre('Copa de Durazno', ['duraznos', 'crema batida', 'galletas'], 'Alterna duraznos con crema y galleta.'),
      postre('Crema de Vainilla con Cajeta', ['leche', 'vainilla', 'maicena', 'cajeta'], 'Cocina una crema de vainilla y cubre con cajeta.'),
      postre('Mousse de Mango', ['mango', '1 lata de leche condensada', 'crema de leche'], 'Licúa el mango con la crema hasta espesar.'),
      postre('Copa de Nuez', ['nuez molida', 'leche condensada', 'crema batida'], 'Mezcla nuez con crema y monta en copas.'),
      postre('Gelatina Cremosa de Fresa', ['gelatina de fresa', 'leche condensada', 'crema de leche'], 'Mezcla gelatina disuelta con la crema.'),
    ],
  },
  {
    id: 'combos',
    title: 'Combos y Kits Dulces',
    image: '/dulces/combos.png',
    description: 'Ideas para vender más por pedido y aumentar el valor de cada compra. 20 recetas.',
    recipes: [
      combo('Caja Degustación (12 dulces)', '1 caja', ['4 brigadeiros surtidos', '4 tartaletas mini', '2 pasteles en vaso pequeños', '2 bolis gourmet']),
      combo('Combo Familiar', '1 combo', ['20 brigadeiros surtidos', '6 bolis gourmet', '1 pastel en vaso grande']),
      combo('Kit de Brigadeiros x25', '1 caja', ['25 brigadeiros surtidos', 'capacillos decorativos', 'etiqueta con tu marca']),
      combo('Combo de Bolis x10', '1 combo', ['10 bolis de sabores variados', 'empaque térmico', 'etiqueta']),
      combo('Caja San Valentín', '1 caja', ['6 brigadeiros de fresa', '4 tartaletas de chocolate', 'tarjeta romántica']),
      combo('Kit Cumpleaños', '1 kit', ['1 pastel en vaso grande', '10 brigadeiros', '5 bolis', 'velita']),
      combo('Combo Fin de Semana', '1 combo', ['8 pasteles en vaso', '10 brigadeiros', 'descuento por volumen']),
      combo('Caja Premium', '1 caja', ['6 brigadeiros gourmet', '4 tartaletas gourmet', '2 postres fríos', 'empaque elegante']),
      combo('Kit para Fiestas', '1 kit', ['50 brigadeiros surtidos', '20 bolis', 'charola de presentación']),
      combo('Combo Cafetería', '1 combo', ['6 tartaletas', '6 pasteles en vaso', 'ideal para acompañar café']),
      combo('Caja de Regalo', '1 caja', ['9 brigadeiros surtidos', 'moño y tarjeta', 'empaque de regalo']),
      combo('Combo Día de las Madres', '1 combo', ['1 postre frío grande', '6 brigadeiros', '4 tartaletas', 'tarjeta']),
      combo('Kit Empresarial', '1 kit', ['30 brigadeiros con logo', 'empaque personalizado', 'tarjeta corporativa']),
      combo('Combo Merienda', '1 combo', ['4 pasteles en vaso', '6 brigadeiros', '2 bolis']),
      combo('Caja Surtida Mini', '1 caja', ['6 brigadeiros mini', '3 tartaletas mini', '3 bolis mini']),
      combo('Combo Navideño', '1 combo', ['brigadeiros temáticos', 'tartaletas de frutos rojos', 'empaque navideño']),
      combo('Kit Antojo Nocturno', '1 kit', ['4 postres fríos', '6 brigadeiros', 'entrega a domicilio']),
      combo('Combo Pareja', '1 combo', ['2 postres fríos', '4 brigadeiros', '2 bolis', 'tarjeta']),
      combo('Caja Corporativa', '1 caja', ['24 brigadeiros surtidos', 'empaque con logo', 'presentación premium']),
      combo('Kit Emprendedora', '1 kit', ['muestra de cada categoría', 'lista de precios sugerida', 'etiquetas de marca']),
    ],
  },
]

export type Bonus = {
  title: string
  image: string
  description: string
  items: string[]
  file: string
  fileLabel: string
}

export const bonuses: Bonus[] = [
  {
    title: 'Menú Pronto de Dulces Brasileños',
    image: '/dulces/bonus-1.png',
    description: 'Un menú editable listo para enviar a tus clientes por WhatsApp.',
    items: [
      'Lista organizada por categorías',
      'Espacio para tus precios',
      'Diseño listo para compartir',
    ],
    file: '/bonos/menu-pronto.pdf',
    fileLabel: 'Ver menú',
  },
  {
    title: 'Lista de Ingredientes Económicos',
    image: '/dulces/bonus-2.png',
    description: 'Todo lo que necesitas comprar para empezar gastando poco.',
    items: [
      'Ingredientes base para todas las recetas',
      'Dónde ahorrar en cada compra',
      'Rendimiento aproximado por ingrediente',
    ],
    file: '/bonos/lista-ingredientes.pdf',
    fileLabel: 'Ver lista',
  },
  {
    title: 'Calculadora Simple de Precio',
    image: '/dulces/bonus-3.png',
    description: 'Aprende a cobrar el precio correcto y ganar en cada venta.',
    items: [
      'Cómo calcular el costo por unidad',
      'Margen de ganancia recomendado',
      'Ejemplos de precios sugeridos',
    ],
    file: '/bonos/calculadora-precio.pdf',
    fileLabel: 'Ver guía',
  },
  {
    title: 'Etiquetas Listas para Imprimir',
    image: '/dulces/bonus-4.png',
    description: 'Etiquetas bonitas para que tus dulces se vean profesionales.',
    items: [
      'Diseños listos para imprimir',
      'Espacio para tu marca',
      'Varios tamaños incluidos',
    ],
    file: '/bonos/etiquetas-imprimir.pdf',
    fileLabel: 'Ver etiquetas',
  },
  {
    title: 'Ideas de Combos para Vender Más',
    image: '/dulces/bonus-5.png',
    description: 'Estrategias para aumentar el valor de cada pedido.',
    items: [
      'Combos que más venden',
      'Ideas para fechas especiales',
      'Cómo ofrecer sin bajar tu ganancia',
    ],
    file: '/bonos/ideas-combos.pdf',
    fileLabel: 'Ver ideas',
  },
]

// Lista de compras organizada por sección
export type ShoppingGroup = {
  id: string
  title: string
  items: string[]
}

export const shoppingList: ShoppingGroup[] = [
  {
    id: 'lacteos',
    title: 'Lácteos',
    items: [
      'Leche condensada',
      'Crema de leche (media crema)',
      'Leche entera',
      'Leche en polvo',
      'Mantequilla sin sal',
      'Queso crema',
      'Yogur natural',
    ],
  },
  {
    id: 'chocolates',
    title: 'Chocolates y Cacao',
    items: [
      'Chocolate en polvo 50% cacao',
      'Cocoa amarga',
      'Chocolate semiamargo para fundir',
      'Chocolate blanco',
      'Chispas de chocolate',
      'Chocolate de leche',
    ],
  },
  {
    id: 'frutas',
    title: 'Frutas',
    items: [
      'Fresas',
      'Plátano',
      'Maracuyá (fruta de la pasión)',
      'Piña',
      'Mango',
      'Limón',
      'Coco fresco o en trozo',
    ],
  },
  {
    id: 'toppings',
    title: 'Coco y Toppings',
    items: [
      'Coco rallado',
      'Granillo de chocolate (chispas)',
      'Grageas de colores',
      'Galletas tipo María',
      'Galletas de chocolate',
      'Nueces y cacahuate',
      'Dulce de leche / cajeta',
    ],
  },
  {
    id: 'envases',
    title: 'Envases y Empaques',
    items: [
      'Bolsas para boli (5x23 cm)',
      'Vasos individuales con tapa',
      'Capacillos de papel',
      'Cajas para regalo',
      'Etiquetas adhesivas',
      'Moños y cintas',
      'Cucharitas desechables',
    ],
  },
  {
    id: 'utensilios',
    title: 'Utensilios',
    items: [
      'Olla mediana antiadherente',
      'Batidor de globo',
      'Cuchara de madera',
      'Vaso medidor',
      'Embudo para rellenar',
      'Moldes de tartaleta',
      'Espátula de silicón',
    ],
  },
]

// Tips para vender
export type SellingTip = {
  icon: 'calc' | 'camera' | 'whatsapp' | 'home' | 'combo' | 'present'
  title: string
  text: string
  points: string[]
}

export const sellingTips: SellingTip[] = [
  {
    icon: 'calc',
    title: 'Cómo calcular tu precio',
    text: 'Cobra bien desde el inicio para que cada venta te deje ganancia real.',
    points: [
      'Suma el costo de todos los ingredientes por unidad.',
      'Multiplica ese costo por 3 como precio base de venta.',
      'Ajusta según tu zona y la presentación del dulce.',
    ],
  },
  {
    icon: 'camera',
    title: 'Cómo sacar buenas fotos',
    text: 'Una buena foto vende sola. Usa luz natural y fondos limpios.',
    points: [
      'Toma las fotos de día, cerca de una ventana.',
      'Usa un fondo claro y sin desorden.',
      'Acerca la cámara para mostrar la textura del dulce.',
    ],
  },
  {
    icon: 'whatsapp',
    title: 'Cómo vender por WhatsApp',
    text: 'Convierte tus contactos en clientes con mensajes claros y directos.',
    points: [
      'Crea un catálogo con fotos y precios.',
      'Publica en tus estados 2 o 3 veces por semana.',
      'Responde rápido y ofrece entrega o punto de encuentro.',
    ],
  },
  {
    icon: 'home',
    title: 'Cómo ofrecer en tu colonia',
    text: 'Tus primeras ventas están más cerca de lo que crees.',
    points: [
      'Ofrece muestras a vecinos y conocidos.',
      'Deja volantes con tu número en tiendas locales.',
      'Pide a tus clientes que te recomienden.',
    ],
  },
  {
    icon: 'combo',
    title: 'Cómo montar combos',
    text: 'Los combos aumentan el valor de cada pedido sin bajar tu ganancia.',
    points: [
      'Combina tus dulces más vendidos.',
      'Ofrece un pequeño descuento por combo.',
      'Crea combos temáticos para fechas especiales.',
    ],
  },
  {
    icon: 'present',
    title: 'Cómo presentar los dulces',
    text: 'La presentación hace que tus dulces se vean premium y se vendan mejor.',
    points: [
      'Usa envases limpios y del tamaño correcto.',
      'Agrega una etiqueta con tu marca.',
      'Cuida los detalles: moños, colores y limpieza.',
    ],
  },
]

// Precios sugeridos
export type PriceRow = {
  name: string
  cost: string
  price: string
  margin: string
  occasion: string
}

export const priceTable: PriceRow[] = [
  { name: 'Boli de chocolate cremoso', cost: '$4', price: '$15 a $25', margin: '≈ 70%', occasion: 'Días calurosos y escuelas' },
  { name: 'Boli de fresa con leche', cost: '$4', price: '$15 a $25', margin: '≈ 70%', occasion: 'Ventas por pedido' },
  { name: 'Brigadeiro tradicional', cost: '$3', price: '$8 a $15', margin: '≈ 65%', occasion: 'Fiestas y cajas de regalo' },
  { name: 'Brigadeiro gourmet', cost: '$5', price: '$12 a $20', margin: '≈ 65%', occasion: 'Eventos y bodas' },
  { name: 'Pastel en vaso', cost: '$12', price: '$30 a $50', margin: '≈ 60%', occasion: 'Pedidos individuales' },
  { name: 'Tartaleta gourmet', cost: '$8', price: '$20 a $35', margin: '≈ 60%', occasion: 'Mesas de postres' },
  { name: 'Postre frío en copa', cost: '$10', price: '$25 a $45', margin: '≈ 60%', occasion: 'Fechas especiales' },
  { name: 'Combo dulce (6 piezas)', cost: '$35', price: '$80 a $200', margin: '≈ 55%', occasion: 'Regalos y celebraciones' },
]
